2024-01-27 09:34:10.482 [info] ERROR:pygls.protocol:Failed to handle request 1 textDocument/documentSymbol DocumentSymbolParams(text_document=TextDocumentIdentifier(uri='file:///home/irene/gits/Projects/PythonMain/test.py'), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request
    self._send_response(msg_id, handler(params))
                                ^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 435, in document_symbol
    jedi_script = jedi_utils.script(server.project, document)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 118, in script
    return Script(code=document.source, path=document.path, project=project)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/__init__.py", line 119, in __init__
    self._inference_state = InferenceState(
                            ^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/inference/__init__.py", line 87, in __init__
    environment = project.get_environment()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/project.py", line 245, in get_environment
    self._environment = create_environment(self._environment_path, safe=False)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 367, in create_environment
    return Environment(_get_executable_path(path, safe=safe), env_vars=env_vars)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 380, in _get_executable_path
    raise InvalidPythonEnvironment("%s seems to be missing." % python)
jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.

2024-01-27 09:34:10.500 [info] [Error - 9:34:10 AM] Request textDocument/documentSymbol failed.
2024-01-27 09:34:10.500 [info]   Message: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
  Code: -32602 
{'traceback': ['  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 435, in document_symbol\n    jedi_script = jedi_utils.script(server.project, document)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 118, in script\n    return Script(code=document.source, path=document.path, project=project)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/__init__.py", line 119, in __init__\n    self._inference_state = InferenceState(\n                            ^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/inference/__init__.py", line 87, in __init__\n    environment = project.get_environment()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/project.py", line 245, in get_environment\n    self._environment = create_environment(self._environment_path, safe=False)\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 367, in create_environment\n    return Environment(_get_executable_path(path, safe=safe), env_vars=env_vars)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 380, in _get_executable_path\n    raise InvalidPythonEnvironment("%s seems to be missing." % python)\n']}
2024-01-27 09:34:10.501 [info] ERROR:pygls.protocol:Failed to handle request 2 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///home/irene/gits/Projects/PythonMain/test.py'), range=0:0-3:15, context=CodeActionContext(diagnostics=[], only=None, trigger_kind=<CodeActionTriggerKind.Automatic: 2>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request
    self._send_response(msg_id, handler(params))
                                ^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 549, in code_action
    jedi_script = jedi_utils.script(server.project, document)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 118, in script
    return Script(code=document.source, path=document.path, project=project)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/__init__.py", line 119, in __init__
    self._inference_state = InferenceState(
                            ^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/inference/__init__.py", line 87, in __init__
    environment = project.get_environment()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/project.py", line 245, in get_environment
    self._environment = create_environment(self._environment_path, safe=False)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 367, in create_environment
    return Environment(_get_executable_path(path, safe=safe), env_vars=env_vars)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 380, in _get_executable_path
    raise InvalidPythonEnvironment("%s seems to be missing." % python)
jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.

2024-01-27 09:34:10.501 [info] [Error - 9:34:10 AM] Request textDocument/codeAction failed.
2024-01-27 09:34:10.501 [info]   Message: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
  Code: -32602 
{'traceback': ['  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 549, in code_action\n    jedi_script = jedi_utils.script(server.project, document)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 118, in script\n    return Script(code=document.source, path=document.path, project=project)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/__init__.py", line 119, in __init__\n    self._inference_state = InferenceState(\n                            ^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/inference/__init__.py", line 87, in __init__\n    environment = project.get_environment()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/project.py", line 245, in get_environment\n    self._environment = create_environment(self._environment_path, safe=False)\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 367, in create_environment\n    return Environment(_get_executable_path(path, safe=safe), env_vars=env_vars)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 380, in _get_executable_path\n    raise InvalidPythonEnvironment("%s seems to be missing." % python)\n']}
2024-01-27 09:34:11.285 [info] ERROR:pygls.protocol:Failed to handle request 3 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///home/irene/gits/Projects/PythonMain/test.py'), range=0:352-0:352, context=CodeActionContext(diagnostics=[], only=None, trigger_kind=<CodeActionTriggerKind.Automatic: 2>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request
    self._send_response(msg_id, handler(params))
                                ^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 549, in code_action
    jedi_script = jedi_utils.script(server.project, document)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 118, in script
    return Script(code=document.source, path=document.path, project=project)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/__init__.py", line 119, in __init__
    self._inference_state = InferenceState(
                            ^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/inference/__init__.py", line 87, in __init__
    environment = project.get_environment()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/project.py", line 245, in get_environment
    self._environment = create_environment(self._environment_path, safe=False)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 367, in create_environment
    return Environment(_get_executable_path(path, safe=safe), env_vars=env_vars)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 380, in _get_executable_path
    raise InvalidPythonEnvironment("%s seems to be missing." % python)
jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.

2024-01-27 09:34:11.286 [info] [Error - 9:34:11 AM] Request textDocument/codeAction failed.
2024-01-27 09:34:11.286 [info]   Message: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
  Code: -32602 
{'traceback': ['  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 549, in code_action\n    jedi_script = jedi_utils.script(server.project, document)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 118, in script\n    return Script(code=document.source, path=document.path, project=project)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/__init__.py", line 119, in __init__\n    self._inference_state = InferenceState(\n                            ^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/inference/__init__.py", line 87, in __init__\n    environment = project.get_environment()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/project.py", line 245, in get_environment\n    self._environment = create_environment(self._environment_path, safe=False)\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 367, in create_environment\n    return Environment(_get_executable_path(path, safe=safe), env_vars=env_vars)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 380, in _get_executable_path\n    raise InvalidPythonEnvironment("%s seems to be missing." % python)\n']}
2024-01-27 09:34:11.637 [info] ERROR:pygls.protocol:Failed to handle request 4 textDocument/documentSymbol DocumentSymbolParams(text_document=TextDocumentIdentifier(uri='file:///home/irene/gits/Projects/PythonMain/test.py'), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request
    self._send_response(msg_id, handler(params))
                                ^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 435, in document_symbol
    jedi_script = jedi_utils.script(server.project, document)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 118, in script
    return Script(code=document.source, path=document.path, project=project)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/__init__.py", line 119, in __init__
    self._inference_state = InferenceState(
                            ^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/inference/__init__.py", line 87, in __init__
    environment = project.get_environment()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/project.py", line 245, in get_environment
    self._environment = create_environment(self._environment_path, safe=False)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 367, in create_environment
    return Environment(_get_executable_path(path, safe=safe), env_vars=env_vars)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 380, in _get_executable_path
    raise InvalidPythonEnvironment("%s seems to be missing." % python)
jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.

2024-01-27 09:34:11.638 [info] [Error - 9:34:11 AM] Request textDocument/documentSymbol failed.
2024-01-27 09:34:11.638 [info]   Message: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
  Code: -32602 
{'traceback': ['  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 435, in document_symbol\n    jedi_script = jedi_utils.script(server.project, document)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 118, in script\n    return Script(code=document.source, path=document.path, project=project)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/__init__.py", line 119, in __init__\n    self._inference_state = InferenceState(\n                            ^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/inference/__init__.py", line 87, in __init__\n    environment = project.get_environment()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/project.py", line 245, in get_environment\n    self._environment = create_environment(self._environment_path, safe=False)\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 367, in create_environment\n    return Environment(_get_executable_path(path, safe=safe), env_vars=env_vars)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 380, in _get_executable_path\n    raise InvalidPythonEnvironment("%s seems to be missing." % python)\n']}
2024-01-27 09:34:12.296 [info] ERROR:pygls.protocol:Failed to handle request 5 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///home/irene/gits/Projects/PythonMain/test.py'), range=0:352-0:352, context=CodeActionContext(diagnostics=[], only=None, trigger_kind=<CodeActionTriggerKind.Automatic: 2>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request
    self._send_response(msg_id, handler(params))
                                ^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 549, in code_action
    jedi_script = jedi_utils.script(server.project, document)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 118, in script
    return Script(code=document.source, path=document.path, project=project)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/__init__.py", line 119, in __init__
    self._inference_state = InferenceState(
                            ^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/inference/__init__.py", line 87, in __init__
    environment = project.get_environment()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/project.py", line 245, in get_environment
    self._environment = create_environment(self._environment_path, safe=False)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 367, in create_environment
    return Environment(_get_executable_path(path, safe=safe), env_vars=env_vars)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 380, in _get_executable_path
    raise InvalidPythonEnvironment("%s seems to be missing." % python)
jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.

2024-01-27 09:34:12.297 [info] [Error - 9:34:12 AM] Request textDocument/codeAction failed.
2024-01-27 09:34:12.297 [info]   Message: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
  Code: -32602 
{'traceback': ['  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 549, in code_action\n    jedi_script = jedi_utils.script(server.project, document)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 118, in script\n    return Script(code=document.source, path=document.path, project=project)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/__init__.py", line 119, in __init__\n    self._inference_state = InferenceState(\n                            ^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/inference/__init__.py", line 87, in __init__\n    environment = project.get_environment()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/project.py", line 245, in get_environment\n    self._environment = create_environment(self._environment_path, safe=False)\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 367, in create_environment\n    return Environment(_get_executable_path(path, safe=safe), env_vars=env_vars)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 380, in _get_executable_path\n    raise InvalidPythonEnvironment("%s seems to be missing." % python)\n']}
2024-01-27 09:34:23.925 [info] ERROR:pygls.protocol:Failed to handle request 6 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///home/irene/gits/Projects/PythonMain/test.py'), range=0:0-3:15, context=CodeActionContext(diagnostics=[Diagnostic(range=0:0-0:1, message='SyntaxError: invalid syntax (test.py, line 1)', severity=<DiagnosticSeverity.Error: 1>, code=None, code_description=None, source='compile', tags=None, related_information=None, data=None)], only=None, trigger_kind=<CodeActionTriggerKind.Automatic: 2>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request
    self._send_response(msg_id, handler(params))
                                ^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 549, in code_action
    jedi_script = jedi_utils.script(server.project, document)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 118, in script
    return Script(code=document.source, path=document.path, project=project)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/__init__.py", line 119, in __init__
    self._inference_state = InferenceState(
                            ^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/inference/__init__.py", line 87, in __init__
    environment = project.get_environment()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/project.py", line 245, in get_environment
    self._environment = create_environment(self._environment_path, safe=False)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 367, in create_environment
    return Environment(_get_executable_path(path, safe=safe), env_vars=env_vars)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 380, in _get_executable_path
    raise InvalidPythonEnvironment("%s seems to be missing." % python)
jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.

2024-01-27 09:34:23.926 [info] [Error - 9:34:23 AM] Request textDocument/codeAction failed.
2024-01-27 09:34:23.926 [info]   Message: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
  Code: -32602 
{'traceback': ['  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 549, in code_action\n    jedi_script = jedi_utils.script(server.project, document)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 118, in script\n    return Script(code=document.source, path=document.path, project=project)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/__init__.py", line 119, in __init__\n    self._inference_state = InferenceState(\n                            ^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/inference/__init__.py", line 87, in __init__\n    environment = project.get_environment()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/project.py", line 245, in get_environment\n    self._environment = create_environment(self._environment_path, safe=False)\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 367, in create_environment\n    return Environment(_get_executable_path(path, safe=safe), env_vars=env_vars)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 380, in _get_executable_path\n    raise InvalidPythonEnvironment("%s seems to be missing." % python)\n']}
2024-01-27 09:34:24.199 [info] ERROR:pygls.protocol:Failed to handle request 7 textDocument/documentSymbol DocumentSymbolParams(text_document=TextDocumentIdentifier(uri='file:///home/irene/gits/Projects/PythonMain/test.py'), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request
    self._send_response(msg_id, handler(params))
                                ^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 435, in document_symbol
    jedi_script = jedi_utils.script(server.project, document)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 118, in script
    return Script(code=document.source, path=document.path, project=project)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/__init__.py", line 119, in __init__
    self._inference_state = InferenceState(
                            ^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/inference/__init__.py", line 87, in __init__
    environment = project.get_environment()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/project.py", line 245, in get_environment
    self._environment = create_environment(self._environment_path, safe=False)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 367, in create_environment
    return Environment(_get_executable_path(path, safe=safe), env_vars=env_vars)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 380, in _get_executable_path
    raise InvalidPythonEnvironment("%s seems to be missing." % python)
jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.

2024-01-27 09:34:24.200 [info] [Error - 9:34:24 AM] Request textDocument/documentSymbol failed.
2024-01-27 09:34:24.201 [info]   Message: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
  Code: -32602 
{'traceback': ['  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 435, in document_symbol\n    jedi_script = jedi_utils.script(server.project, document)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 118, in script\n    return Script(code=document.source, path=document.path, project=project)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/__init__.py", line 119, in __init__\n    self._inference_state = InferenceState(\n                            ^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/inference/__init__.py", line 87, in __init__\n    environment = project.get_environment()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/project.py", line 245, in get_environment\n    self._environment = create_environment(self._environment_path, safe=False)\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 367, in create_environment\n    return Environment(_get_executable_path(path, safe=safe), env_vars=env_vars)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 380, in _get_executable_path\n    raise InvalidPythonEnvironment("%s seems to be missing." % python)\n']}
2024-01-27 09:34:24.934 [info] ERROR:pygls.protocol:Failed to handle request 8 textDocument/codeAction CodeActionParams(text_document=TextDocumentIdentifier(uri='file:///home/irene/gits/Projects/PythonMain/test.py'), range=0:0-3:15, context=CodeActionContext(diagnostics=[], only=None, trigger_kind=<CodeActionTriggerKind.Automatic: 2>), work_done_token=None, partial_result_token=None)
Traceback (most recent call last):
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request
    self._send_response(msg_id, handler(params))
                                ^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 549, in code_action
    jedi_script = jedi_utils.script(server.project, document)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 118, in script
    return Script(code=document.source, path=document.path, project=project)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/__init__.py", line 119, in __init__
    self._inference_state = InferenceState(
                            ^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/inference/__init__.py", line 87, in __init__
    environment = project.get_environment()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/project.py", line 245, in get_environment
    self._environment = create_environment(self._environment_path, safe=False)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 367, in create_environment
    return Environment(_get_executable_path(path, safe=safe), env_vars=env_vars)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 380, in _get_executable_path
    raise InvalidPythonEnvironment("%s seems to be missing." % python)
jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.

2024-01-27 09:34:24.935 [info] [Error - 9:34:24 AM] Request textDocument/codeAction failed.
2024-01-27 09:34:24.935 [info]   Message: jedi.api.environment.InvalidPythonEnvironment: bin/python seems to be missing.
  Code: -32602 
{'traceback': ['  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 340, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/pygls/protocol.py", line 264, in _execute_request\n    self._send_response(msg_id, handler(params))\n                                ^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 549, in code_action\n    jedi_script = jedi_utils.script(server.project, document)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 118, in script\n    return Script(code=document.source, path=document.path, project=project)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/__init__.py", line 119, in __init__\n    self._inference_state = InferenceState(\n                            ^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/inference/__init__.py", line 87, in __init__\n    environment = project.get_environment()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/project.py", line 245, in get_environment\n    self._environment = create_environment(self._environment_path, safe=False)\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 367, in create_environment\n    return Environment(_get_executable_path(path, safe=safe), env_vars=env_vars)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/irene/.vscode-oss/extensions/ms-python.python-2023.22.1-universal/pythonFiles/lib/jedilsp/jedi/api/environment.py", line 380, in _get_executable_path\n    raise InvalidPythonEnvironment("%s seems to be missing." % python)\n']}
